[package]
name = "rust-redis"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
bytes = "1"
thiserror = "1"
anyhow = "1.0.100"
rand = "0.8"
serde = { version = "1" , features = ["derive"]}
serde_json = "1"
